### PR TITLE
#274 iOS - UI - Add left delete action to item

### PR DESCRIPTION
**Pull request by jancy123**
#274 iOS - UI - Add left delete action to item

https://github.com/WomenWhoCode/WWCodeMobile/assets/13859276/a9141cc5-f130-4de4-8eae-c5daf678d467

### CODE REVIEW

**Comment by jancy123** [comment]
Please review @clc80 @devanshimodha

**Comment by vuinguyen** [comment]
@clc80 @devanshimodha I wanted to bring to your attention that we now have 2 PRs open for the same feature, the swipe left to delete feature.

There is this PR #276, connected to issue #274. 
There is also PR #259, connected and issue #239. 

I personally like what was done in PR #259 with the Confirmation Pop Up Dialog, and that PR was completed first. But for some reason, that PR did not get reviewed.

It's up to you two which PR to review and approve. But I would suggest that for whichever PR you DO review, please close the other PR explaining that it is a duplicate, to avoid confusion please

**Comment by clc80** [comment]
> @clc80 @devanshimodha I wanted to bring to your attention that we now have 2 PRs open for the same feature, the swipe left to delete feature.
> 
> There is this PR #276, connected to issue #274. There is also PR #259, connected and issue #239.
> 
> I personally like what was done in PR #259 with the Confirmation Pop Up Dialog, and that PR was completed first. But for some reason, that PR did not get reviewed.
> 
> It's up to you two which PR to review and approve. But I would suggest that for whichever PR you DO review, to please close the _other PR_ explaining that it is a duplicate. This will help avoid confusion with having two open PRs for the same feature.

@vuinguyen Devanshi and I talked about these two issues in our meeting. They are not the same issue, they are similar but not the same. 

This issue is just the left swipe to delete. The other issue is more than just deleting. It's a done button to mark the task as being done. It won't delete it will move them to another screen, like a history screen where a user can look at them again.

**Review by clc80 — APPROVED** [review]
Great job

**Comment by vuinguyen** [comment]
@jancy123 sorry there was some miscommunication and there is already an older PR open for the swipe to delete feature. Thank you for your work on this! I will close this PR now because it is a duplicate.

**Pull request closed without merging**
