### PR TITLE
[iOS][#190] - Integration - Add Time Activity

### PR DESCRIPTION
**Pull request by jancy123**
[#190] - Integration - Add Time Activity
Sorted the activity to match wireframe and removed unneeded code.

Screenshot 2024-03-03 at 10 19 17 PM

### CODE REVIEW

**Comment by jancy123** [comment]
@clc80 @devanshimodha  pls review. This is all what I found missing from wireframe for this issue. Please let me know if there was anything more that was expected from the issue.

**Comment by clc80** [comment]
> @clc80 @devanshimodha pls review. This is all what I found missing from wireframe for this issue. Please let me know if there was anything more that was expected from the issue.

@ceceliacreates what else did you expect from this issue, I don't recall talking about these integration issues.

**Comment by ceceliacreates** [comment]
@clc80 The integration issues were created in case that contributors wanted to work on UI and logic issues separately, and then "connect" them after. If there is nothing else needed to ensure the "Add Time Activity" flow is complete, then we can move forward and close the issue. Sorry for any confusion!

**Review by ceceliacreates — APPROVED** [review]
This looks good to me, just removes commented out code and adds .reversed() method to the sort.

**Pull request merged**
