### PR TITLE
Android-issue-77 Edit timed activity (update logic)

### PR DESCRIPTION
**Pull request by jyoshna-joshi**
Screenshot 2024-03-04 104054
Screenshot 2024-03-04 104126

closes issue #77 

@renweview @gaurigadkari @baghaii my PR is ready for review !

## Write a brief description of what your PR accomplished
* How did your PR fix the issue mentioned above? What files were changed or created? What did your changes do?
I've implemented a logic update in the detail screen where users can edit the date, time, and title of a task, ensuring that these changes are reflected in the database for that specific task. To accomplish this, I've utilized ROOM and integrated Hilt for dependency injections.
In the process, I've organized related files into a package-local structure, creating new files like LocalTask and TaskState while relocating AppDatabase and TaskDao into the same folder.
Additionally, I've established an ITaskRepository interface, and structured a "di" package containing DataModules for dependency injection.
Updates were applied to both the TaskDetailScreen and TaskDetailViewModel classes to accommodate these changes.
Furthermore, I've created a TaskApplication class to needed for Hilt setup.

## TODO: Attach screenshots of your changes
* This could be the screens from running the app in the simulator, or in the IDE UI Preview window.

## Explain how to test your PR
* For example, what unit tests need to be run, if any? What buttons do you need to tap on which screens to test the app flow?
I've added a method called createNewTask() within the TaskDetailViewModel for testing purposes, which have static values right now and need to be removed later. This method can be invoked from the DetailScreen by creating a new button. Upon clicking this button it will add task with id =1 for now. If the changes are made to the inputs or clicked the values, the database will be updated once the user clicks the "done" button.

### CODE REVIEW

**Comment by baghaii** [comment]
This PR is too large and doing too many things. It also creates a bunch of merge conflicts.

Can you create a new issue that just adds Hilt to the project and create a single PR to just add hilt?

Another person is working on adding Room right now so I don't want this PR to mess up the work that they are doing.

**Comment by jyoshna-joshi** [comment]
@baghaii  How about I rework my code after their Room is merged so that there won't be any conflicts? Hilt is used in other common classes potentially leading to recurring issues.

**Comment by gaurigadkari** [comment]
@jyoshna-joshi let's table adding hilt until it is absolutely necessary, we can do this in phase 2
Also like Sepideh said this is a a very busy PR trying to do too much, lets break it in to smaller PRs which will make it easier to review and get it merged sooner
Focus on MVP related issues first
cc @baghaii

**Comment by renweview** [comment]
closing per request

**Pull request closed without merging**
