### PR TITLE
Issue #211 Update PR Template to Add Guidance on PR Title

### PR DESCRIPTION
**Pull request by vuinguyen**
Implements issue #211 

This PR provides guidance on the PR template for naming the PR title and also the branch title

Can I get a review @clc80 and @ceceliacreates when you get a chance please?

### CODE REVIEW

**Review by gaurigadkari — COMMENTED** [review]
Should we also have a section to mention some details of what changes this PR is making

**Comment by vuinguyen** [comment]
> Should we also have a section to mention some details of what changes this PR is making

@gaurigadkari if you take a look at the entire template file, there is already a 
"TODO: Write a brief description of what your PR accomplished" section. See [link ](https://github.com/WomenWhoCode/WWCodeMobile/blob/f88581c4009689f3f5281f3b93e810e8298b8a85/pull_request_template.md#todo-write-a-brief-description-of-what-your-pr-accomplished)

This PR is adding more information to the existing PR template 😊 for writing the PR Title

**Review by clc80 — CHANGES_REQUESTED** [review]
Maybe instead of using IOS in both examples we could use android in one, or also give an example of an android issue.

**Comment by vuinguyen** [comment]
> Maybe instead of using IOS in both examples we could use android in one, or also give an example of an android issue.

@clc80 I made the recommended changes, and removed TODOs so that the PR template is consistent with the issue template, which you also reviewed.

**Comment by vuinguyen** [comment]
@clc80 Please review again when you get a chance. Thanks!

**Comment by ceceliacreates** [comment]
@clc80 @gaurigadkari we need one more approval before it can be merged, can either of you review? Thank you!

**Review by clc80 — APPROVED** [review]

**Pull request merged**
