### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gaurigadkari**
Updated the setup section
https://github.com/WomenWhoCode/WWCodeMobile/issues/63

### CODE REVIEW

**Review by vuinguyen — APPROVED** [review]
@gaurigadkari I checked all the links, and they work! 

That is a great idea to post links to resources instead of creating all this content yourself. 🎉

**Comment by vuinguyen** [comment]
@gaurigadkari Before merging, can you add the link to the issue for this PR? Or create an issue if one doesn't exist, so we can track our work on the projects. Thanks!

**Comment by vuinguyen** [comment]
Thanks for adding the issue to this PR @gaurigadkari ! Make sure to check off the setup section of the issue https://github.com/WomenWhoCode/WWCodeMobile/issues/63 once this PR is merged

**Review by renweview — APPROVED** [review]
Thank you for adding those details. For future PRs it would be great to include a 'beginner friendly' PR section as well.

**Pull request merged**
