### PR TITLE
Group Projects Folder Structure

### PR DESCRIPTION
**Pull request by vuinguyen**
Closes issue #52

### CODE REVIEW

**Comment by vuinguyen** [comment]
Additional Comments:

- I could not create empty folders for the different coding projects, as I couldn't check those into version control. 

- Therefore, I had to create some README placeholder files in each of the coding project folders, in order to check in the folder structure. I added TODO comments in the README placeholder files, stating that they need to be fleshed out later.
 
- I also added some resources (links to recording and slides) to the open source maintenance and open source contributions workshops. 

- I added a placeholder README template in the resources (with a TODO to complete it later), as well as a README at the top level of the project folder.

All this was needed in order to put an initial projects folder structure in place, for the upcoming group projects. More work needs to be done in the future, to flesh out the content within the subfolders, of course, but at least this PR get that folder structure in place.

**Review by jackiechanmakes — COMMENTED** [review]
This is what I would suggest looking over the PR:
-  The structure looks good and is what Regina and I came up with for our talk.
-  I personally would rename 'projects' to 'coding-projects' as the highest level directory folder. It would be more descriptive and meaningful given the names already used for the other folders in our github repo. We have 'projects' when it comes to the book study groups that are generally one-off exercises.
- There's a discrepancy in how you named your files. Everything is in kebab-case except for the /slides files which are in PascalCase. Was that intentional? I generally prefer kebab-case as it's easier/faster for people to navigate through repo when using the command line.
- In the /projects README.md, there's a missing space preventing formatting to be the same across all projects. It currently is '/mobile-game:' contains when you probably meant to put '/mobile-game : contains'
- I personally would capitalize all README.md headers (e.g. Resources, [Coding] Projects, Android Project, iOS Project, Mobile Game Project, Project XYZ). I think it looks better and makes the formatting more in sync across the projects. It currently is 'iOS', 'Android', 'mobile game' and it looks off to me that mobile game is currently lower cased while the others are upper cased as appropriate. I also think it's easier to read, but this styling is just a personal preference. 
- Last thing I'll note is that generally it's best practice for commit messages to have first word capitalized and written in the imperative mood (e.g. 'Add high level README.md file for projects folder' instead of 'high level README.md file for projects folder') unless you're going for what's called 'conventional commits'. If you would like to do that, there are online sources that outline how those would look like and, if using that convention, the commit message would be all lowercased. This is a minor point and I don't particularly care as compared to the content of the files themselves, but admittedly following best practices would keep git log clean for future readers & helps workflow

**Comment by vuinguyen** [comment]
@jackiechanmakes I made some changes based on your suggestions. Thanks for your review!

Your note on the commit messages is new to me:

> Last thing I'll note is that generally it's best practice for commit messages to have first word capitalized and written in the imperative mood

although I will try to adopt this practice.

Your comments make me think that in addition to the code contribution guidelines for each project (which will be project dependent, of course) that we may need to have a documentation contribution guidelines as well. I am torn as to finding the right balance in providing guidelines: make it too strict and it becomes a barrier to participating, and don't provide enough guidance and you spend too much time reviewing PRs based on style instead of content. I tend to be a little more flexible when it comes to enforcing consistent style, myself 😊.

If I were to create some issues for writing contribution guidelines, READMEs, etc. can I assign those to you? I think you have a good idea of how you'd like things structured in the repos, so maybe we should start with your ideas first. And then, we can have one or two of the lead maintainers review your PRs, so we can get a discussion going. What do you think? Would you be open to that?

**Comment by vuinguyen** [comment]
@jackiechanmakes my PR is ready for a second review! 🙏🏼

**Comment by jackiechanmakes** [comment]
I am good with being flexible with enforcing styling so it's not a barrier for participating.

**Review by jackiechanmakes — APPROVED** [review]

**Review by jackiechanmakes — APPROVED** [review]

**Review by vuinguyen — COMMENTED** [review]
Jackie approved my changes but I still can't merge. Let me see if I can review my own PR, so I can merge

**Comment by vuinguyen** [comment]
@jackiechanmakes I've requested you to have merge access. I can also merge my PR now. But can you test out your access by merging my PR? 🙏🏼

**Pull request merged**
